language: c

compiler:
  - gcc

addons:
  apt:
    packages:
      - valgrind
      - cppcheck
      - make
      - cmake
      - lcov

before_script:
  - cd DZ1/Google_tests
  - mkdir lib
  - cd lib
  - git submodule add -f https://github.com/google/googletest.git
  - cd ..
  - cd ..

  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake; here we assume that the project's
  # top-level CMakeLists.txt is located at '..'

script:
  # static lib
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DCMAKE_C_FLAGS="--coverage" -DCMAKE_CXX_FLAGS="--coverage"
  - make
  - ./tests/Google_Tests_run
  - valgrind --tool=memcheck --leak-check=yes ./tests/Google_Tests_run
  # shared lib
  -
  - lcov --capture --directory . --output-file coverage.info
  - bash <(curl -s https://codecov.io/bash)
  - cd ..
  - cd src
  - cppcheck --enable=warning,performance,information *.c