language: c

compiler:
  - gcc

addons:
  apt:
    packages:
      - valgrind
      - cppcheck
      - make
      - cmake
      - lcov

before_script:
  - cd test
  - git submodule add -f https://github.com/google/googletest.git
  - cd ..

  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake; here we assume that the project's
  # top-level CMakeLists.txt is located at '..'

script:
  # static googletest
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DCMAKE_C_FLAGS="--coverage" -DCMAKE_CXX_FLAGS="--coverage"
  - make
  - ./test/Google_Tests_run
  - valgrind --tool=memcheck --leak-check=yes ./test/Google_Tests_run
  # shared googletest
  - cd ..
  - rm -rf build
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DCMAKE_C_FLAGS="--coverage" -DCMAKE_CXX_FLAGS="--coverage" -DMULTITHREADING:BOOL=ON
  - whereis pthread
  - make
  - ./test/Google_Tests_run
  - valgrind --tool=memcheck --leak-check=yes ./test/Google_Tests_run
  - lcov --capture --directory . --output-file coverage.info
  - bash <(curl -s https://codecov.io/bash)
  - cd ..
  - cd project
  - cppcheck --enable=warning,performance,information my_array/*.c my_list/*.c *.c